/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.shufange.hibernatemavenproject;

import com.shufange.hibernatemavenproject.model.*;
import java.util.List;

/**
 *
 * @author shufange
 */
public class GUI extends javax.swing.JFrame {
    
    private final Service service = new Service();
    /**
     * Creates new form NewJFrame
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addEmployeeFirstName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        addEmployeeLastName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addEmployeeSalary = new javax.swing.JTextField();
        addEmployeeConfirmButton = new javax.swing.JButton();
        addEmployeeCancelButton = new javax.swing.JButton();
        addEmployeeDialogFeedbackLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        companyPanelTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        companyAddButton = new javax.swing.JButton();
        companyDeleteButton = new javax.swing.JButton();
        companySearchButton = new javax.swing.JButton();
        companyListAllButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        employeePanelTextField3 = new javax.swing.JTextField();
        employeeAddButton = new javax.swing.JButton();
        employeeDeleteButton = new javax.swing.JButton();
        employeeSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        employeePanelTextField1 = new javax.swing.JTextField();
        employeeListButton = new javax.swing.JButton();
        employeePanelTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jDialog1.setSize(new java.awt.Dimension(315, 220));

        jLabel8.setText("Employee information:");

        jLabel9.setText("First Name:");

        jLabel7.setText("Last Name:");

        jLabel10.setText("Salary:");

        addEmployeeConfirmButton.setText("Add Employee");
        addEmployeeConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeConfirmButtonActionPerformed(evt);
            }
        });

        addEmployeeCancelButton.setText("Cancel");
        addEmployeeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addEmployeeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addEmployeeLastName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addComponent(addEmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addEmployeeConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addEmployeeCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(addEmployeeDialogFeedbackLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addEmployeeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addEmployeeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addEmployeeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addEmployeeDialogFeedbackLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmployeeConfirmButton)
                    .addComponent(addEmployeeCancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Company");

        jLabel2.setText("Please enter company name or id:");

        companyPanelTextField.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CID", "Company"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        companyAddButton.setText("Add");
        companyAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyAddButtonActionPerformed(evt);
            }
        });

        companyDeleteButton.setText("Delete");
        companyDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyDeleteButtonActionPerformed(evt);
            }
        });

        companySearchButton.setText("Search");
        companySearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companySearchButtonActionPerformed(evt);
            }
        });

        companyListAllButton.setText("ListAll");
        companyListAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyListAllButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter employee Id/Name/Salary:");

        employeePanelTextField3.setToolTipText("");

        employeeAddButton.setText("Add Employee");
        employeeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeAddButtonActionPerformed(evt);
            }
        });

        employeeDeleteButton.setText("Delete Employee");
        employeeDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDeleteButtonActionPerformed(evt);
            }
        });

        employeeSearchButton.setText("Search");
        employeeSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Employee");

        jLabel5.setText("Company Id/Name:");

        employeePanelTextField1.setToolTipText("");

        employeeListButton.setText("List Employee");
        employeeListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeListButtonActionPerformed(evt);
            }
        });

        employeePanelTextField2.setToolTipText("");

        jLabel6.setText("Employee Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(companyPanelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(companyDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(companyListAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeePanelTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(employeeSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeePanelTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(employeePanelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(304, 304, 304))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(companyPanelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeePanelTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeListButton)
                            .addComponent(employeeAddButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(companyAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(companySearchButton)
                                    .addComponent(companyListAllButton)))
                            .addComponent(companyDeleteButton))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeeDeleteButton)
                            .addComponent(employeePanelTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(employeePanelTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeSearchButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDeleteButtonActionPerformed
        String employeeidinput = employeePanelTextField2.getText().trim();
        if(employeeidinput==null || employeeidinput.length()==0 
                || employeeidinput.equals("Enter valid id!")
                || !service.isValidInteger(employeeidinput)
                || service.searchEmployee(employeeidinput).size()==0){
            
            employeePanelTextField2.setText("Enter valid id!");
            
        }else{
            service.deleteEmployee(employeeidinput);
            List<Employee> employees = service.listEmployee();
            generateEmployeeTable(employees);
        }     
    }//GEN-LAST:event_employeeDeleteButtonActionPerformed

    private void employeeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeAddButtonActionPerformed
        String companyidinput = employeePanelTextField1.getText().trim();
        if(companyidinput==null || companyidinput.length()==0 
                || companyidinput.equals("Enter valid id!")
                || !service.isValidInteger(companyidinput)
                || service.searchCompany(companyidinput).size()==0){
            employeePanelTextField1.setText("Enter valid id!");
        }else{
            jDialog1.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_employeeAddButtonActionPerformed

    private void companyListAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyListAllButtonActionPerformed
        generateCompanyTable(service.listCompany());
    }//GEN-LAST:event_companyListAllButtonActionPerformed

    private void companySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companySearchButtonActionPerformed
        String input = companyPanelTextField.getText().trim();
        if(input==null || input.length()==0 || input.equals("Enter valid id or name!")){
            companyPanelTextField.setText("Enter valid id or name!");
        }else{
            generateCompanyTable(service.searchCompany(input));
        }
    }//GEN-LAST:event_companySearchButtonActionPerformed

    private void companyDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyDeleteButtonActionPerformed
        String input = companyPanelTextField.getText().trim();
        if(input==null || input.length()==0 || input.equals("Enter valid id or name!")){
            companyPanelTextField.setText("Enter valid id or name!");
        }else{
            service.deleteCompany(input);
            generateCompanyTable(service.listCompany());
        }
    }//GEN-LAST:event_companyDeleteButtonActionPerformed

    private void companyAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyAddButtonActionPerformed
        String input = companyPanelTextField.getText().trim();
        if(input==null || input.length()==0 || input.equals("Enter valid id or name!")){
            companyPanelTextField.setText("Enter valid id or name!");
        }else{
            service.addCompany(input);
            generateCompanyTable(service.listCompany());
        }
    }//GEN-LAST:event_companyAddButtonActionPerformed

    private void employeeListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeListButtonActionPerformed
        String companyidinput = employeePanelTextField1.getText().trim();
        if(companyidinput==null || companyidinput.length()==0 
                || companyidinput.equals("Enter valid id!")
                || !service.isValidInteger(companyidinput)
                || service.searchCompany(companyidinput).size()==0){
            employeePanelTextField1.setText("Enter valid id!");
        }else{
            List<Company> company = service.searchCompany(companyidinput);
            List<Employee> employees = service.listEmployee(company.get(0));
            generateEmployeeTable(employees);
        }
    }//GEN-LAST:event_employeeListButtonActionPerformed

    private void addEmployeeConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeConfirmButtonActionPerformed
        String companyId = employeePanelTextField1.getText().trim();
        String firstName = addEmployeeFirstName.getText().trim();
        String lastName = addEmployeeLastName.getText().trim();
        String salary = addEmployeeSalary.getText().trim();
        
        if(firstName==null || firstName.length()==0 || firstName.length()>30
                || firstName.equals("Enter first name!")){
            addEmployeeFirstName.setText("Enter first name!");
        }
        else if(lastName==null || lastName.length()==0 || lastName.length()>30
                || lastName.equals("Enter first name!")){
            addEmployeeLastName.setText("Enter last name!");
        }
        else if(salary==null || salary.length()==0 || !service.isValidInteger(salary)
                || salary.equals("Enter number only!")){
            addEmployeeSalary.setText("Enter number only!");
        }
        else{
            try{
                service.addEmployee(companyId, firstName, lastName, Integer.parseInt(salary));
                addEmployeeFirstName.setText("");
                addEmployeeLastName.setText("");
                addEmployeeSalary.setText("");
                jDialog1.setVisible(false);
                List<Company> company = service.searchCompany(companyId);
                List<Employee> employees = service.listEmployee(company.get(0));
                generateEmployeeTable(employees);
            }catch(Exception ex){
                addEmployeeDialogFeedbackLabel.setText("Failed to add!");
            }
        }
        
    }//GEN-LAST:event_addEmployeeConfirmButtonActionPerformed

    private void addEmployeeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeCancelButtonActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_addEmployeeCancelButtonActionPerformed

    private void employeeSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchButtonActionPerformed
        String searchinput = employeePanelTextField3.getText().trim();
        if(searchinput==null || searchinput.length()==0 
                || searchinput.equals("Enter employee id or name!")){
            employeePanelTextField3.setText("Enter employee id or name!");
        }else{
            generateEmployeeTable(service.searchEmployee(searchinput));         
        }
    }//GEN-LAST:event_employeeSearchButtonActionPerformed

    private void generateCompanyTable(List<Company> companies){
        Object [][] table =  new Object [companies.size()][2];
        for(int i=0;i<companies.size();i++){
            Company company = companies.get(i);
            table[i][0] = company.getCompanyId();
            table[i][1] = company.getCompanyName();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            table,
            new String [] {
                "CID", "Company"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    private void generateEmployeeTable(List<Employee> employees){
        Object [][] table =  new Object [employees.size()][4];
        for(int i=0;i<employees.size();i++){
            Employee employee = employees.get(i);
            table[i][0] = employee.getEmployeeId();
            table[i][1] = employee.getFirstName();
            table[i][2] = employee.getLastName();
            table[i][3] = employee.getSalary();
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            table,
            new String [] {
                "ID", "First Name", "Last Name", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeCancelButton;
    private javax.swing.JButton addEmployeeConfirmButton;
    private javax.swing.JLabel addEmployeeDialogFeedbackLabel;
    private javax.swing.JTextField addEmployeeFirstName;
    private javax.swing.JTextField addEmployeeLastName;
    private javax.swing.JTextField addEmployeeSalary;
    private javax.swing.JButton companyAddButton;
    private javax.swing.JButton companyDeleteButton;
    private javax.swing.JButton companyListAllButton;
    private javax.swing.JTextField companyPanelTextField;
    private javax.swing.JButton companySearchButton;
    private javax.swing.JButton employeeAddButton;
    private javax.swing.JButton employeeDeleteButton;
    private javax.swing.JButton employeeListButton;
    private javax.swing.JTextField employeePanelTextField1;
    private javax.swing.JTextField employeePanelTextField2;
    private javax.swing.JTextField employeePanelTextField3;
    private javax.swing.JButton employeeSearchButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
